### ISSUE TITLE
Schedule doodle poll for officer outing

### ISSUE THREAD

**Issue by linamoon** [uxutdallas/officeroutings#1]
- Topgolf (discounts from Cathy?)
- Movie and a dinner 
- Rock climbing
- Art museum (Perot, DMA wine tasting) and dinner!
- Paintball (club would buy ammunition)
- King Spa/Spa Castle

**Comment by linamoon** [comment]
Website for Doodle can be found here: 
- http://doodle.com/
Plan for  Feb 6 - 12, ideally weekend (?)

**Comment by angelakou** [comment]
Are we supposed to fill out a Doodle? If so, where can I find the link?

**Comment by uxutd** [comment]
@caathytraan should have sent you an email invite - will also ask her to
share the link on Slack!

**Comment by linamoon** [comment]
@caathytraan - please repost Doodle link on Slack #general so that officers can fill out additional days.

**Comment by caathytraan** [comment]
http://doodle.com/poll/ivcwyksq872a7sse This is the link to the poll, please let me know if you have any questions.
